# **Project Title: Data scientist salary**

## Importing Libraries

In [1]:
#pandas library use to load dataset and also manipulate tabular data
import pandas as pd
#numpy library use to do array operations and also to do calculations
import numpy as np
#matplot library use to plot different graphs
import matplotlib.pyplot as plt
#seaborn library use to plot differentplots
import seaborn as sns
# figure size in inches
from matplotlib import rcParams
#importing stats model to add intercept and to implement OLS
import statsmodels.api as sm
#importing sklearn for split data
from sklearn.model_selection import train_test_split
from statsmodels.tools.eval_measures import rmse
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# importing random lib for replace age values
import random

### Here we are importing dataset by using pandas

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
# read the dataset:

df=pd.read_csv("data_cleaned_2021.csv")

In [ ]:
salary=df #creating new data frame

In [ ]:
pd.options.display.max_columns=None

In [ ]:
# Here we are checking data is loaded or not and also checking top 5 observations
salary.head()

As in our dataset we have "-1" as null values so we replace them with nan but some are object columns and some are int columns. so we have to replace to both

In [ ]:
salary.shape#Checking shape of columns

In [ ]:
salary=salary.replace(['-1'],[np.nan])

In [ ]:
salary=salary.replace([-1],[np.nan])

In [ ]:
salary.Rating.unique() # As we see there is -1 value present in rating column. -1 is not valid rating so we check frequency of -1

In [ ]:
# As data is always in raw format so we have to clear data and for that we have to check mainly data types of all columns
salary.info()

In [ ]:
#As for prediction there is no reqyuirement of index column so we are dropping that column
salary = salary.drop("index",axis=1)

In [ ]:
salary.shape #checking column drop or not first we have 42 columns currently we have 41

## EDA

In [ ]:
salary["Company Name"].value_counts()

In [ ]:
salary.head(2)

In [ ]:
# As we can see in above data that some columns are repeat like comapany_txt and Job location. Data present in these two columns 
# are same as location and Job title. So we are dropping both columns 
salary.columns

In [ ]:
salary.isnull().sum()

As our data frame contains missing values name as "-1" So to handle missing values we check missing values column data type i.e. "Object" so we replace it with mode

First Handle categorical columns null values

In [ ]:
salary["Competitors"] = salary["Competitors"].fillna(salary["Competitors"].mode()[0])

In [ ]:
salary["Industry"] = salary["Industry"].fillna(salary["Industry"].mode()[0])

In [ ]:
salary["Sector"] = salary["Sector"].fillna(salary["Sector"].mode()[0])

In [ ]:
salary["Headquarters"] = salary["Headquarters"].fillna(salary["Headquarters"].mode()[0])

Second we handle numeric columns null values

In [ ]:
# Lets look at how the 'Rating' column is distributed:

plt.figure(figsize=(8,5))
plt.title('\n Distribution of Rating Column \n', size=16, color='black')
plt.xlabel('\n Rating \n', fontsize=13, color='black')
plt.ylabel('\n Density\n', fontsize=13, color='black')
plt.xticks(fontsize=13)
plt.yticks(fontsize=12)
sns.distplot(salary.Rating,color="black")
plt.show()

It follows a normal distribution, therefore we can replace null values with the mean of the distribution.

In [ ]:
salary["Rating"] = salary["Rating"].fillna(salary["Rating"].mean())

In [ ]:
# Lets look at how the 'Age' column is distributed:

plt.figure(figsize=(8,5))
plt.title('\n Distribution of Age Column \n', size=16, color='black')
plt.xlabel('\n Age \n', fontsize=13, color='black')
plt.ylabel('\n Density\n', fontsize=13, color='black')
plt.xticks(fontsize=13)
plt.yticks(fontsize=12)
sns.distplot(salary.Age,color="black")
plt.show()

As we can see data is right skewed we replace null values with median.

In [ ]:
salary["Age"] = salary["Age"].fillna(salary["Age"].median())

In [ ]:
# Lets look at how the 'Founded' column is distributed:

plt.figure(figsize=(8,5))
plt.title('\n Distribution of Founded Column \n', size=16, color='black')
plt.xlabel('\n Founded \n', fontsize=13, color='black')
plt.ylabel('\n Density\n', fontsize=13, color='black')
plt.xticks(fontsize=13)
plt.yticks(fontsize=12)
sns.distplot(salary.Founded,color="black")
plt.show()

As we can see data is left skewed we replace null values with median.

In [ ]:
salary["Founded"].median()

In [ ]:
salary["Founded"] = salary["Founded"].fillna(salary["Founded"].median())

At last check we check is there any null values or not

In [ ]:
salary.isnull().sum()

There are no missing values in data frame so we can proceed to our next EDA

In [ ]:
salary.describe() #checking statistics of numeric variable

In above summary statistics we get mean value and all quartile values of all columns and as well as min, max values. So following are observations:

   1.Average lower salary is about 75 K pa. We see 75% of the jobs positing has minimum salary =< than 91K pa, so it doesn't look like the mean value is affected much by the outlier(15K or 202K pa).

   2.Average maximum salary is around 128K pa. We see 75% of the jobs positing has maximum salary =< than 155K pa, so it doesn't look like the mean value is affected much by the outlier(16K or 306K pa).
   
   3.Mean Avg. salary is about 101K pa.


In given data set there are two columns namely "Location" and "Job Location". In Location column city name and state abbreviation given and in location column only state abreviation given. So first we will check abbreviation and location column last state abbrevaition

There are two columns named as company name and company txt so we will check difference and work on them

In [ ]:
salary["Company Name"]

In [ ]:
salary["Company Name"]=salary["Company Name"].str[:-4] #"company Name column contains name with rating also so we are removing rating given in that column"

In [ ]:
salary["Company Name"]

In [ ]:
salary["company_txt"]

In [ ]:
salary['compare'] = (salary['Company Name'] == salary['company_txt'])
salary['compare']

In [ ]:
salary['compare'].value_counts()# checking both column values are same or not but we get to know that 11 are different values

checking False values to change their company name

In [ ]:
salary[salary["compare"]==False]

In [ ]:
print(salary[salary["compare"]==False].index.values)

In [ ]:
print(salary[salary["Company Name"]=="Kronos"].index.values)

In [ ]:
df.loc[[370,404,551,609,641,730]] # checking original data frame company name values as we reduced name by 4 letters from right side

as in above original dataframe comapany name of above index values is "Kronos Bio" so we replace them

In [ ]:
salary.loc[[370,404,551,609,641,730], 'Company Name'] = "Kronos Bio"

In [ ]:
salary.loc[[370,404,551,609,641,730]] # checking company name changed or not for given index values

In [ ]:
df.loc[[176,266]]

In [ ]:
salary.loc[[176,266], 'Company Name'] = "CA-One Tech Cloud" #As name gets reduced so we will change name of above index

In [ ]:
df.loc[[300,456]]

For "300" and "456" index there is no name so we change original company name for 300 and 456

In [ ]:
salary.loc[[300], 'Company Name'] = "Muso"

In [ ]:
salary.loc[[456], 'Company Name'] = "ALIN"

Again checking is there any False values

In [ ]:
salary['compare'] = (salary['Company Name'] == salary['company_txt'])

In [ ]:
salary['compare'].value_counts()

As seen in above in company name and company text both are same. There are some False values which have last word alphabet not present in "company_txt" column.So we drop company text column and also compare column which we have created for crosscheck

In [ ]:
salary.drop("compare",axis=1,inplace=True)
salary.drop("company_txt",axis=1,inplace=True)

In [ ]:
salary.columns

In [ ]:
#Here we made new column derived for take out state abrevation
salary["Location_abb"]=salary["Location"].str[-2:]

In [ ]:
#Here we checking derived abbrevaition of state and present column named as job location
salary["Check"]=salary["Job Location"].equals(salary["Location_abb"])

In [ ]:
salary["Check"].value_counts() #Here we get to know that job location column is not useful so we are drop that column

We dropped "location" column as abbrevaition same

In [ ]:
salary.drop("Location",axis=1,inplace=True) 
salary.drop("Location_abb",axis=1,inplace=True)
salary.drop("Check",axis=1,inplace=True) # Here we drop location as well as location_abb and check column also

In [ ]:
salary.shape#checking column dropped or not

In [ ]:
salary.seniority_by_title.value_counts()

In [ ]:
salary.Degree.value_counts()

In [ ]:
# We check relation between degree and avg salary

In [ ]:
sns.barplot(y="Avg Salary(K)",x="Degree",data=salary)
#Beautifying the plot

plt.title('\n Degree and Salary Relationship Plot \n', size=30, color='black')
plt.xticks(fontsize=25)
plt.yticks(fontsize=25)
plt.xlabel('\n Degree \n', fontsize=20, color='black')
plt.ylabel('\n Avg Salary(K) \n', fontsize=20, color='black')
plt.show()

As above we get to know that more salary will be given to PHD holders also we check with seniority

In [ ]:
sns.barplot(y="Avg Salary(K)",x="seniority_by_title",data=salary)
#Beautifying the plot

plt.title('\n seniority_by_title and Salary Relationship Plot \n', size=30, color='black')
plt.xticks(fontsize=25)
plt.yticks(fontsize=25)
plt.xlabel('\n seniority_by_title \n', fontsize=20, color='black')
plt.ylabel('\n Avg Salary(K) \n', fontsize=20, color='black')
plt.show()

As we get to know that salary will be higher for senior and PHD holder person

Checking outlier in age column

In [ ]:
sns.boxplot(x="Age",data=salary)

As there are outliers in Age column and above we seen that Age column is right skewed so we have to handle outliers by IQR method

In [ ]:
Q1=salary["Age"].quantile(0.25)
Q3=salary["Age"].quantile(0.75)
IQR=Q3-Q1
print(IQR)

In [ ]:
Q1

In [ ]:
Q3

In [ ]:
pd.options.display.max_columns=None

In [ ]:
salary.loc[salary['Age'] < 14 , 'Age'] = random.randint(14,67)

In [ ]:
salary.loc[salary['Age'] > 67 , 'Age'] = random.randint(14,67)

In [ ]:
salary.shape #Here we check that column dropped or not

In [ ]:
correlation=salary.corr()

In [ ]:
correlation=salary.corr()
# set the plot size
plt.figure(figsize = (35,25))
# plot the heat map
# correlation: give the correlation matrix
# cmap: color code used for plotting
# annot_kws: sets the font size of the annotation
# annot: prints the correlation values in the chart
# vmax: gives a maximum range of values for the chart
# vmin: gives a minimum range of values for the chart
sns.heatmap(correlation,annot = True, vmax = 1.0, vmin = -1.0, cmap = 'bwr', annot_kws = {"size": 18})
# set the size of x and y axes labels using 'fontsize'
plt.xticks(fontsize = 18)
plt.yticks(fontsize = 18)
plt.show()

In above correlation heat map we get know that only some columns are morely correlated like upper salary,lower salary and avg salary but at time of model building we will not consider lower salary and upper salary

In [ ]:
salary["Avg Salary(K)"].max()

In [ ]:
salary[salary["Avg Salary(K)"]==254]["Job Location"]

As above we get to know that highest salary available in Illinois state

In [ ]:
# Making a dataframe with only 3 columns: Job Location, Lower Salary and Upper Salary.

A=salary.groupby("Job Location")["Lower Salary","Upper Salary"].mean().reset_index()
A

In [ ]:
salary["Job Location"].value_counts()

In [ ]:
plt.figure(figsize=(50,20))
sns.barplot(x=salary["Job Location"].value_counts().index[0:10], y = salary["Job Location"].value_counts()[0:10],)
plt.title('\n States with Most Number of Jobs \n', size=50, color='black')
plt.xticks(fontsize=30)
plt.yticks(fontsize=30)
plt.xlabel('\n States \n', fontsize=40, color='black')
plt.ylabel('\n Count \n', fontsize=40, color='black')
plt.show()

As per above plot we get to know that maximum jobs available in California state.

In [ ]:
salary.shape

In [ ]:
salary.columns

Average Salary in Different States.

In [ ]:
#Making a DF of Average Salary of top 10 states in which job postings was maximum.

B = salary.groupby("Job Location")["Avg Salary(K)"].mean().sort_values(ascending=False)[0:10]
B = B.reset_index().rename(columns={"Job Location":"Location","Avg Salary(K)":"Average Salary"})

In [ ]:
B

In [ ]:
salary["Job Location"].nunique()

In [ ]:
# Plotting the average salary per annum for different states.
sns.barplot(y="Location", x = "Average Salary",data=B)

As per above graph we get to know that avg salary is more in California state

Relation between Average Salary and Education

In [ ]:
pd.pivot_table(salary, index = 'job_title_sim', columns = "Degree", values = 'Avg Salary(K)', 
               aggfunc = ['mean','count']).rename(columns={"mean":"Avg Salary(K)"})

-Most of the companies has mentioned Masters degree in their job descriptions.

-For companies that mentioned a PhD degree in their job description, they offered much highes average annual salary as compared to Masters.

In [ ]:
# According to my opinion job description will not be play role in salary prediction so I am droppig that column

In [ ]:
salary.drop("Job Description",axis=1,inplace=True)

What are the top skills for each job title?

In [ ]:
skill_labels = ['Python', 'spark', 'aws', 'excel', 'sql', 'sas', 'keras', 'pytorch',
                'scikit', 'tensor', 'hadoop', 'tableau', 'bi', 'flink', 'mongo', 'google_an']
skills_by_title = salary.groupby('job_title_sim')[skill_labels].sum()
skills_by_title

It looks like Python and SQL are the top skills in demand for Data Scientists, Data Engineers,analyst and Machine Learning Engineers. Excel is also a good skill to have for many of the jobs listed.

How does salary break down by company size?

In [ ]:
salary_labels = ['Lower Salary', 'Upper Salary', 'Avg Salary(K)']
salary_by_co_size = salary.groupby('Size')[salary_labels].mean()
salary_by_co_size

As observed above largest companies can afford to pay the best.

In [ ]:
df1=salary.groupby('Sector')['Avg Salary(K)'].mean().sort_values(ascending=False)
plt.figure(figsize = (15,8))
df1.plot.bar()

As observed above we get to know that highest avg salary available in media sector

In [ ]:
df2=salary.groupby('job_title_sim')['Avg Salary(K)'].mean().sort_values(ascending=False)
plt.figure(figsize = (15,8))
df2.plot.bar()

As above we get to know that after MLE highest salary get to director and Data scientist and data engineer

In [ ]:
salary.shape

In [ ]:
salary.drop("Headquarters",axis=1,inplace=True)# I dropped Headquarter column as I think it not reauired for salary prediction

In [ ]:
salary.drop("Competitors",axis=1,inplace=True)# I dropped Competitors column as I think it not reauired for salary prediction

In [ ]:
salary.drop("Job Title",axis=1,inplace=True)# I dropped Job Title column as we have another column in which they have segregate
#  Job title in main columns

In [ ]:
salary.drop("Salary Estimate",axis=1,inplace=True)# I dropped Salary Estimate column as we have another column "Avg Salary(k)"

In [ ]:
salary.drop("Industry",axis=1,inplace=True) # As Industry gets divide into sector so I am dropping Industry column

In [ ]:
salary.drop("Hourly",axis=1,inplace=True)
salary.drop("Employer provided",axis=1,inplace=True)# as both column not required for salary prediction so we will drop them

In [ ]:
salary.drop("Lower Salary",axis=1,inplace=True)
salary.drop("Upper Salary",axis=1,inplace=True)#As Lower salary and upper salary are correlated and it doesn't take into consideration while predict wo we will drop

In [ ]:
salary.columns

In [ ]:
salary.drop("Company Name",axis=1,inplace=True)

In [ ]:
salary.shape

In [ ]:
len(salary.Sector.value_counts())

In [ ]:
salary["Type of ownership"].value_counts()

In [ ]:
salary.Revenue.value_counts()

In [ ]:
sns.barplot(y="Revenue",x="Avg Salary(K)",data=salary)

In [ ]:
salary1=salary

we creating another data frame we will build a model on both in "salary1" we will drop remaining columns only include skills and on"salary we will do OHE encoding and build a model

Filter numerical and categorical variables

In [ ]:
df_numeric = salary.select_dtypes(include=np.number)

In [ ]:
df_numeric.head()

In [ ]:
df_numeric.shape

In [ ]:
df_categoric = salary.select_dtypes(include = object)

In [ ]:
df_categoric.head()

In [ ]:
df_categoric.shape

Dummy encode the catergorical variables

In [ ]:
dummy_encoded_variables = pd.get_dummies(df_categoric, drop_first = True)

In [ ]:
dummy_encoded_variables.head()

In [ ]:
dummy_encoded_variables.shape

Concatenate numerical and dummy encoded categorical variables

In [ ]:
# concatenate the numerical and dummy encoded categorical variables column-wise
df_dummy = pd.concat([df_numeric, dummy_encoded_variables], axis=1)

# display data with dummy variables
df_dummy.head()

In [ ]:
# add the intercept column using 'add_constant()'
df_dummy = sm.add_constant(df_dummy)

# separate the independent and dependent variables
# drop(): drops the specified columns
X = df_dummy.drop(["Avg Salary(K)"], axis = 1)

# extract the target variable from the data set
y = df_dummy[["Avg Salary(K)"]]

In [ ]:
y

## 1.Linear Regression

In [ ]:
x=X[['Age','Rating','Degree_P']]
y=df['Avg Salary(K)']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(x_train,y_train)

In [ ]:
print('Co-efficients',lm.coef_)

In [ ]:
predictions=lm.predict(x_test)

Prediction of Output

In [ ]:
plt.scatter(y_test,predictions)
plt.xlabel('Y_test')
plt.ylabel('Predicted Outcome')

## Model Evaluation

In [ ]:
from sklearn import metrics
print('MAE:',metrics.mean_absolute_error(y_test,predictions))
print('MSE:',np.square(np.subtract(y_test,y_train)).mean())
print('RMSE:',np.sqrt(metrics.mean_squared_error(y_test,predictions)))

In [ ]:
sns.displot((y_test,predictions),bins=50)

In [ ]:
coefficient=pd.DataFrame(lm.coef_,x.columns)
coefficient.columns=['coeffcient']
print(coefficient)

# 2D.Linear Regression using SVD

In [ ]:
# importing library min max scaler to scale data
from sklearn.preprocessing import MinMaxScaler
#import library for implement Linear Regression
from sklearn.linear_model import SGDRegressor 
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler= StandardScaler()

In [ ]:
scaler.fit(X)

In [ ]:
X1

In [ ]:
y1=y

In [ ]:
y1

In [ ]:
# split data into train data and test data 
# what proportion of data should be included in test data is passed using 'test_size'
# set 'random_state' to get the same data each time the code is executed 
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.2, random_state = 1)

# check the dimensions of the train & test subset for 
# print dimension of predictors train set
print("The shape of X1_train is:",X1_train.shape)

# print dimension of predictors test set
print("The shape of X1_test is:",X1_test.shape)

# print dimension of target train set
print("The shape of y1_train is:",y1_train.shape)

# print dimension of target test set
print("The shape of y1_test is:",y1_test.shape)

In [ ]:
# build the model
SGD_model = SGDRegressor(loss="squared_loss",alpha = 0.1, max_iter = 3000) #Instantiation

# fit the model
SGD_model.fit(X1_train, y1_train) #Training

In [ ]:
# predict the values
y1_pred_SGD  = SGD_model.predict(X1_test)

In [ ]:
y1_pred_SGD

In [ ]:
plt.scatter(y1_test,y1_pred_SGD)
plt.xlabel('Targets' ,size = 18)
plt.ylabel('Predictions',size = 18)
plt.show()

In [ ]:
r_squared_SGD = SGD_model.score(X1_train,y1_train)
# Number of observation or sample size
n = 817
# No of independent variables
p = 119
#Compute Adj-R-Squared
Adj_r_squared_SGD = 1 - (1-r_squared_SGD)*(n-1)/(n-p-1)
# Compute RMSE
rmse_SGD = sqrt(mean_squared_error(y1_test, y1_pred_SGD))

In [ ]:
# compile the required information
linreg_full_metrics = pd.Series({'Model': "Linear regression with SGD ",
                     'RMSE':rmse_SGD,
                     'R-Squared': r_squared_SGD,
                     'Adj. R-Squared': Adj_r_squared_SGD     
                   })
cols = ['Model', 'RMSE', 'R-Squared', 'Adj. R-Squared']
result_tabulation = pd.DataFrame(columns = cols)
# append our result table using append()
# ignore_index=True: does not use the index labels
# python can only append a Series if ignore_index=True or if the Series has a name
result_tabulation = result_tabulation.append(linreg_full_metrics, ignore_index = True)
# print the result table
result_tabulation